// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"jquery","status":true,"description":"","parameters":{}},
{"name":"MVNotes","status":true,"description":"ウェブ雑記帳プラグイン","parameters":{"host":"mv-notes.herokuapp.com"}}
];
