// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ShowDevTool","status":false,"description":"","parameters":{}},
{"name":"TestPlugin","status":false,"description":"","parameters":{}}
];
